<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le refuge Animalier au coeur des pattes depuis 2023, est une association à but non-lucratif de chiens et de chats.">
    <meta name="author" content="Le refuge au coeur des pattes">
    <title>Au coeur des pattes</title>
    <link rel="icon" type="image/x-icon" href="/final-project/public/assets/front/img/logo.jpg">
    <link rel="stylesheet" type="text/css" href="/final-project/public/assets/front/sass/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body>
 <!-- Navigation-->
<header>
    <nav class="navbar">
        <div class="logo">
            <img class="logo" width="160" height="80" src="/final-project/public/assets/front/img/logo.jpg" alt="Logo au coeur des pattes">
            <label class="logo1">Au Cœur des Pattes</label>
        </div>
        <div class="navlinks">
            <ul>
                 <li><a href="<?= $base_uri[0] ?>/public/home">Accueil</a></li>
                 <li><a href="<?= $base_uri[0] ?>/public/contact">Contact</a></li>
                 <li><a href="<?= $base_uri[0] ?>/public/adopt">J'adopte</a></li>
                 <li><a href="<?= $base_uri[0] ?>/public/about">À propos</a></li>
                 <?php if (!isset($_SESSION['user_id'])): ?>
                 <li><a href="<?= $base_uri[0] ?>/public/login">Connexion</a></li>      
                 <li><a href="<?= $base_uri[0] ?>/public/register">Inscription</a></li>
                 <?php else: ?>
                 <li><a href="<?= $base_uri[0] ?>/public/logout">Deconnexion</a></li>
                 <?php endif; ?>
            </ul>
        </div>
            <svg viewBox="0 0 24 24" width="2em" height="2em" class="burger"><path fill-rule="evenodd" clip-rule="evenodd" d="M21 7.75H3v-1.5h18v1.5zm0 5H3v-1.5h18v1.5zm0 5H3v-1.5h18v1.5z"></path></svg>
    </nav>
</header>
