<!-- Main Content -->
<div id="content">
    
        <!-- Page Heading -->
        <div class="add-animal">
            <h1>Add animal</h1>
        </div>
        <form  method="post">
              <input class="input" type="text" name="name" placeholder="Name">
              <input class="input" type="text" name="sexe" placeholder="Sexe">
              <input class="input" type="number" name="age" placeholder="Age">
              <input class="input" type="text" name="img" placeholder="Img">
              <input class="input" type="text" name="type" placeholder="Type">
              <textarea name="description" rows="10" cols="50"></textarea>
              <input type="submit" name="addAnimal" value="create">
        </form>
</div>
                