<!-- Main Content -->
<div id="content">
    <div class="add-container">
        <div class="add-animal">
            <h1>Ajouter un animal</h1>
        </div>
        <form class="add-form" method="post">
              <input class="input" type="text" name="name" placeholder="Name">
              <input class="input" type="text" name="sexe" placeholder="Sexe">
              <input class="input" type="number" name="age" placeholder="Age">
              <input class="input" type="text" name="img" placeholder="Img">
              <input class="input" type="text" name="type" placeholder="Type">
              <textarea class="input" name="description" rows="10" cols="50" placeholder="Description"></textarea>
              <input class="submit" type="submit" name="addAnimal" value="ajouter">
        </form>
    </div>
</div>
                