<!-- Main Content -->
<div id="content">
                            <div class="row">
                                <a href="<?= $base_uri[0]; ?>/public/add">add animals</a>
                                    <table class="dataTable">
                                        <thead>
                                            <tr>
                                                <th class="name-admin" aria-label="name">name</th>
                                                <th class="sexe-admin" aria-label="sexe">sexe</th>
                                                <th class="age-admin" aria-label="age">age</th>
                                                <th class="img-admin" aria-label="image">image</th>
                                                <th class="description-admin" aria-label="description">description</th>
                                                <th class="status-admin" aria-label="status">status</th>
                                                <th class="type-admin" arial-label="type">type</th>
                                                <th class="date-admin" arial-label="date">date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php foreach ($data['animal'] as $animal) : ?>
                                                <tr>
                                                    <td><?= $animal->getName(); ?></td>
                                                    <td><?= $animal->getAge(); ?></td>
                                                    <td><?= $animal->getSexe(); ?></td>
                                                    <img src="<?= $base_uri[0]; ?>/public/assets/front/img/<?= $animal->getImg() ?>"  width="100" height="100" alt="" ?>
                                                    <td><?= $animal->getDescription(); ?></td>
                                                    <td><?= $animal->getStatus(); ?></td>
                                                    <td><?= $animal->getType(); ?></td>
                                                    <td><?= $animal->getdate(); ?></td>
                                                    <td>
                                                        <form class="delete-animal" action="" method="post">
                                                            <input type="hidden" name="animalid" value="<?= $animal->getId(); ?>">
                                                            <input class="btn btn-primary" name="deleteAnimal" type="submit" value="Delete">
                                                        </form>
                                                    </td>
                                                    <td>                                                                                                                    
                                                        <a class="btn-primary" href="<?= $base_uri[0]; ?>/public/admin/update/<?= $animal->getId(); ?>">Update animal</a>                                                        
                                                    </td>
                                                </tr>
                                            <?php endforeach ?>

                                    </table>
                                </div>
                </div>
</div>