<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Le refuge Animalier au coeur des pattes depuis 2023, est une association à but non-lucratif de chiens et de chats.">
    <meta name="author" content="Le refuge au coeur des pattes">
    <title>Au coeur des pattes</title>
    <link rel="icon" type="image/x-icon" href="/final-project/public/assets/front/img/logo.jpg">
    <link rel="stylesheet" type="text/css" href="/final-project/public/assets/front/sass/styles.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body>
<header>
    <nav class="navbar-admin">
        <div class="logo">
            <img class="logo" width="120" height="80" src="/final-project/public/assets/front/img/logo.jpg" alt="Logo au coeur des pattes"/>
            <label class="logo1">Au Cœur des Pattes</label>
        </div>
        <div class="navlinks">
            <ul>
                 <?php if (!isset($_SESSION['user_id'])): ?>
                 <?php else: ?>
                 <li><a href="<?= $base_uri[0] ?>/public/logout">Deconnexion</a></li>
                 <?php endif; ?>
            </ul>
        </div>
    </nav>
</header>
