<div class="about-container">
<div class="about-content">
<img class="about-first-img" src="/final-project/public/assets/front/img/dog-cat.jpg" alt="Image d'un petit chien et d'un chat jouant dans une forêt">
    <section class="section-1">
        <div class="p-img1">
            <div class="bloc-img3">
                <h1>Qui sommes-nous?</h1>
                <p>Bienvenue chez <span class="red"> "Au Cœur des Pattes"</span>,  un havre de tendresse, de compassion et de protection pour nos amis à quatre pattes. 
                   Notre refuge <span class="red">animalier</span> est bien plus qu'un simple endroit où les <span class="red">animaux</span> trouvent refuge. 
                   C'est un foyer où les cœurs se rencontrent, où les histoires se transforment et où les vies s'épanouissent.
                </p>
            </div>
            <div class="img-section1">
                <img class="border-img" src="/final-project/public/assets/front/img/pattes.jpg" alt="Une main et une patte de chien côte à côte">
            </div>
        </div>
    </section>

    <section class="section-2">
        <div class="p-img2">
            <div class="bloc-img2">
                <h1>Notre histoire :</h1>
                <p>L'histoire de <span class="red">"Au Cœur des Pattes"</span> a débuté avec la passion partagée de quelques individus dévoués, unis par leur amour inconditionnel pour les <span class="red">animaux</span>. 
                   Guidés par la conviction que chaque créature mérite une chance de vivre une vie heureuse.
                </p>
            </div>
            <div class="img-section2">
                <img class="border-img" src="/final-project/public/assets/front/img/amour-chiens.jpg" alt="Un groupe d'amis avec un petit chien au milieu">
            </div>
        </div>
    </section>

    <section class="section-3">
        <div class="p-img3">
            <div class="bloc-img3">
                <h1>Notre engagement :</h1>
                <p>Nous nous engageons à fournir un sanctuaire pour les animaux dans le besoin, qu'ils soient <span class="red">maltraités, abandonnés ou en quête d'une nouvelle famille.</span> 
                   Notre équipe dévouée travaille jour et nuit pour offrir des soins médicaux attentifs, des <span class="red">espaces de vie stimulants</span> et, surtout, une <span class="red">abondance d'amour</span>.
                </p>
            </div>
            <div class="img-section3">
                <img class="border-img" src="/final-project/public/assets/front/img/babycat.jpg" alt="chaton buvant un biberon par sa maîtresse">
            </div>
        </div>
    </section>
</div>

    <!-- Carrousel -->
    <section class="about-carrousel">
        <h1>Nos valeurs :</h1>
        <p><span class="red">Amour</span> et <span class="red">compassion</span> pour les animaux, <span class="red">Adoption responsable</span> et bien-être animal, <span class="red">sensibilisation</span> à la maltraitance animal et l'abandon.</p>
        <div class="slider">
                <img class="img__slider active" src="/final-project/public/assets/front/img/love-dog.jpg" alt="amour inconditionnel envers les chiens et les chats">
                <img class="img__slider" src="/final-project/public/assets/front/img/cat-black.jpg" alt="un chat en noir et blanc">
                <img class="img__slider" src="/final-project/public/assets/front/img/hand.jpg" alt="Une main et une patte de chien">
            <div class="next">
                <i class="fas fa-chevron-circle-right" style="color: #9747FF;"></i>
            </div>
            <div class="previous">
                <i class="fas fa-chevron-circle-left" style="color: #9747FF;";></i>
            </div>
        </div>
    </section>
</div>
