<?php
use App\Models\FavoriModel;
$FavoriModel = new FavoriModel();
?>
<article class="animal">
    <div class="article-content">
        <div class="container-header-subpage">
        <div class="article-identity">
            <div class="article-identity-block">
            <h1>Name: <?= $data->getName() ?></h1>
            <h1>Sexe: <?= $data->getSexe() ?></h1>
            <h1>Age:  <?= $data->getAge()  ?></h1>
            </div>
        </div>
            <img src="<?= $base_uri[0]; ?>/public/assets/front/img/<?= $data->getImg() ?>"  alt="l'image de l'animal cliqué, ça peut-être un chien ou un chat en fonction de ce qu'on a choisi" ?>
        </div>
        <div class="container-main-subpage">
        <div class="content-article">
        <div class="description">
            <h2>Description :</h2> 
            <p><?= $data->getDescription() ?></p>
            <?php if(isset($_SESSION['user_id'])):
            ?>
        <form id="favori-form" method="POST">
            <input type="hidden" name="animal_id" value="<?= $data->getId() ?>">
            <?php
                if($FavoriModel->isFavori($data->getId(),$_SESSION['user_id'])):
            ?>
                <button type="submit" name="remove-fav-button" id="favori-button" style="padding: 10px 20px; cursor: pointer; font-size: 1.5rem; border-radius: 10px; background-color:#fff; border: 2px solid #9747FF; color: #9747FF;">Supprimer des favoris</button>
            <?php
                else:
            ?>
                <button type="submit" name="fav-button" id="favori-button" style="padding: 10px 20px; cursor: pointer; font-size: 1.5rem; border-radius: 10px; background-color:#fff; border: 2px solid #9747FF; color: #9747FF;">❤️ Ajouter aux favoris</button>
            <?php endif; ?>
        </form>
<?php else: ?>
    <p>Connectez vous pour ajouter aux favoris :)</p>
    <?php endif; ?>
        </div>
        <div class="more-information">
            <h2>Informations Complémentaires :</h2>
             <p><?= $data->getStatus() ?></p>
             <p><?= $data->getType() ?></p>
            </div>
        </div>
        </div>
    </div>
</article>




