<div class="contactContainer">
    <h1>Nous contacter</h1>
    <form id="form" class="formContact" method="post">
        <div class="inputGroup">
            <input type="text" id="name" name="name" class="input" placeholder="votre nom..." required>
        </div>
        <div class="inputGroup">
            <input type="email" id="email" class="input" name="email" placeholder="votre email..." required>
        </div>
        <div class="inputGroup">
            <textarea id="message" class="input" name="message" rows="10" cols="33" required>message...</textarea>
        </div>
        <div class="inputSubmit" id="submit">
            <input type="submit" class="Submitbtn" value="Envoyer">
        </div>
        <div class="inputCheckbox">
            <input type="checkbox" class="checkboxbtn">
        </div>
    </form>
    <div class="localisation">
        <h2>Notre Localisation</h2>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3828.4987376224894!2d-2.225597836732836!3d47.2721771944143!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1694607874228!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</div>

<script>
    const form = document.getElementById("form");
    let submit = document.getElementById("submit");
    
    form.addEventListener("submit", function(e){
        e.preventDefault();
        
        submit.classList.add("submitBtnConfirm");
        
        const payload = new FormData(form);
        console.log([...payload]);
        
      fetch("https://eliazbouchon.sites.3wa.io/final-project/public/contact", {
          method: "POST",
          body: payload,
      })
      .then(res => res.json())
      .then(res => console.log(res))
      .then((res) =>{
          if(res.status == true){
              console.log('succes')
          }else if(res.status == false){
              console.log(res.error)
          }
          submit.classList.remove("submitBtnConfirm");
          
      })
    })
</script>