<div class="contact-container">
    <h1>Nous contacter</h1>
    <form id="form" class="form-contact" method="post">
    <div class="input-group">
        <label for="name"></label>
            <input type="text" id="name" name="name" class="input" placeholder="votre nom..." required>
        </div>
    <div class="input-group">
        <label for="email"></label>
            <input type="email" id="email" class="input" name="email" placeholder="votre email..." required>
        </div>
    <div class="input-group">
        <label for="message"></label>
            <textarea id="message" class="input" name="message" rows="10" cols="33" required>message...</textarea>
        </div>
    <div class="input-submit" id="submit">
            <input type="submit" class="Submitbtn" value="Envoyer">
        </div>
    <div class="input-checkbox">
        <input type="checkbox" name="checkbox" class="checkboxbtn" id="rgpdCheckbox">
            <label for="rgpdCheckbox">J'accepte les conditions RGPD</label>
        </div>
        <div id="rgpdValidationMessage"></div>
</form>
    <div id="successMessage" style="color: green;"></div>
    <div id="errorMessage" style="color: red;"></div>
    <figure>
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3828.4987376224894!2d-2.225597836732836!3d47.2721771944143!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sfr!2sfr!4v1694607874228!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        <figcaption>Carte de notre emplacement</figcaption>
    </figure>
</div>

<script>
const form = document.getElementById("form");
const submit = document.getElementById("submit");
const rgpdCheckbox = document.getElementById("rgpdCheckbox");
const rgpdValidationMessage = document.getElementById("rgpdValidationMessage");
const successMessage = document.getElementById("successMessage");
const errorMessage = document.getElementById("errorMessage"); 

form.addEventListener("submit", function(e){
    e.preventDefault();

    if (!rgpdCheckbox.checked) {
        rgpdValidationMessage.textContent = "Veuillez accepter les conditions RGPD pour continuer.";
        return;
    } else {
        rgpdValidationMessage.textContent = "";
    }

    submit.classList.add("submitBtnConfirm");

    const payload = new FormData(form);

    fetch("https://eliazbouchon.sites.3wa.io/final-project/public/contact", {
        method: "POST",
        body: payload,
    })
    .then(res => res.json())
    .then(res =>{
        if(res.status == true){
            form.style.display = 'none';
            successMessage.textContent = "Le message a été envoyé avec succès, un staff du refuge vous répondra au plus vite :).";
            errorMessage.textContent = ""; 
        } else if(res.status == false){
            const errorscontainer = document.getElementById("errors-container");
            
            errorMessage.textContent = "Erreur lors de l'envoi du message : " + res.error; 
        }
        submit.classList.remove("submitBtnConfirm");
    });
});
</script>