<?php
use App\Models\AnimalModel;
$AnimalModel = new AnimalModel();
?>
<h1>Vous êtes sur la page favori</h1>
<div class="animal-column">
        <?php foreach ($this->data as $animal_id) : ?>
            <div class="animal-adopt">
                <?php
                $animal= $AnimalModel->getAnimalById($animal_id['animal_id']);
                ?>
                <a href="animal/<?= $animal->getId() ?>">
                    <img class="adopt-animal" width="100" height="250" src="assets/front/img/<?= $animal->getImg() ?>" alt="chiens ou chats du refuge au coeur des pattes">
                    <h2><?= $animal->getName() ?></h2>
                </a>
        </div>
    <?php endforeach; ?>
</div>