<!-- Page Home-->
<div class="container-home">
    <div class="banner">
        <div class="title-home">
            <h1>Un Foyer pour Chats et Chiens : Où chaque patte trouve sa place</h1>
        </div>
    </div>
<div class="content-home">
    <div class="button-bloc">
            <p>Bienvenue dans notre <span class="red">refuge chaleureux</span>, où chaque miaulement et aboiement trouve un foyer aimant. 
               Nous sommes fiers de vous accueillir dans notre <span class="red">sanctuaire dédié aux chiens et chats</span> en quête d'amour et d'attention.</p>
            <button id="redirection-Button">Voir tous les animaux disponibles à l’adoption</button>
        </div>
    <div class="sad-dog1">
        <img class="sad-dog" src="/final-project/public/assets/front/img/sad-dog1.jpg" alt="première image d'un chien triste">
        <p>L'abandon des chiens et des chats est une triste réalité. Chaque année, de nombreux animaux domestiques se retrouvent livrés à eux-mêmes, laissés sans abri et vulnérables. 
           <span class="red">Cette pratique irresponsable a des conséquences désastreuses pour nos fidèles compagnons à quatre pattes</span>. 
           En les abandonnant, non seulement nous nions leur droit à une vie digne et aimante, mais nous contribuons également à la <span class="red">surpopulation des refuges 
           et à la souffrance</span> de ces animaux innocents. </p>
    </div>
    <div class="sad-cat1">
        <img class="sad-cat" src="/final-project/public/assets/front/img/cat-sad2.jpg" alt="deuxième image un chat triste">
        <p>Il est impératif que nous éduquions sur la responsabilité de la possession d'un animal de compagnie et que nous encouragions <span class="red">l'adoption responsable</span>. 
        En offrant un <span class="red">foyer aimant, des soins appropriés et de l'affection à nos animaux de compagnie</span>, 
        nous pouvons mettre un terme à cette triste réalité et créer un monde où chaque chien et chat a la chance de vivre une vie heureuse et épanouissante.</p>
    </div>
     <div class="sad-dog3">
        <img class="sad-dog2" src="/final-project/public/assets/front/img/sad-dog2.jpg" alt="troisième image un chien triste">
        <p>Les chiens et les chats peuvent avoir un <span class="red">impact émotionnel</span> sur nos vies, que ce soit en tant qu'animaux de compagnie, 
        en relation avec des expériences passées ou dans des contextes plus larges.
        Comment peut-on faire du mal à ces incroyables êtres vivants !? </p>
    </div>
</div>

<script>
  var button = document.getElementById("redirection-Button");

  button.addEventListener("click", function() {
    window.location.href = "https://eliazbouchon.sites.3wa.io/final-project/public/adopt";
  });
</script>

</div>
