<div class="legal-information1">
<h1>Mentions Légales - Refuge Animalier</h1>

<h2>Responsable du site</h2>
<p>Raison sociale : Au Coeur Des Pattes</p>
<p>Statut juridique : Association a but non-lucratif</p>
<p>Adresse : 123 Rue des Animaux Heureux, Ville, Pays</p>
<p>Numéro de téléphone : +XX XX XX XX XX</p>
<p>Email : refuge.aucoeurdespattes@gmail.com</p>

<h2>Hébergement</h2>
<p>Nom de l'hébergeur : Eliaz Bouchon</p>
<p>Adresse de l'hébergeur : 10 Allee des Tulipes</p>
<p>Numéro de téléphone de l'hébergeur : +XX XX XX XX XX</p>

<h2>Protection des Données Personnelles</h2>
<p>Le refuge animalier s'engage à protéger la vie privée de ses utilisateurs. Pour plus d'informations sur la collecte et le traitement des données personnelles, veuillez consulter notre <a href="<?= $base_uri[0] ?>/public/privacypolicy">Politique de Confidentialité</a>.</p>

<h2>Droits de Propriété Intellectuelle</h2>
<p>Tous les contenus de ce site (textes, images, vidéos, etc.) sont la propriété du refuge animalier ou utilisés avec l'autorisation de leurs propriétaires. Toute reproduction ou utilisation non autorisée de ces contenus est interdite.</p>

<h2>Liens Externes</h2>
<p>Ce site peut contenir des liens vers des sites externes. Le refuge animalier n'est pas responsable du contenu ou des pratiques de confidentialité de ces sites.</p>

<h2>Responsabilité</h2>
<p>Le refuge animalier s'efforce de fournir des informations exactes et à jour, mais ne peut garantir l'absence d'erreurs ou d'omissions. Il décline toute responsabilité en cas de préjudice résultant de l'utilisation de ce site.</p>

<h2>Contact</h2>
<p>Pour toute question concernant ces mentions légales, veuillez nous contacter à l'adresse email suivante : refuge.aucoeurdespattes@gmail.com</p>
</div>