<div class="login-container">
<div class="login-container-block">
<img class="img-login" width="280" height="250" src="/final-project/public/assets/front/img/wolf-font.jpg" alt="image loup pour connexion"/>
<div class="login-form">
<h1>Connexion</h1>
<form class="user" action="" method="post">
    
<input type="email" name="email" class="email-form" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email">
                
<input type="password" name="password" class="pass-form" id="exampleInputPassword" placeholder="Mot de passe">
                                
<input type="submit" name="loginForm" class="login-btn" value="Login">

</div>
</form>
</div>
</div>
