<div class="login-container">
<div class="login-container-block">
<img class="img-login" width="280" height="200" src="/final-project/public/assets/front/img/wolf-font.jpg" alt="image loup pour connexion"/>
<h1>Connexion</h1>
<form class="user" action="" method="post">
    
<input type="email" name="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Email">
                
<input type="password" name="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Mot de passe">
                                
<input type="submit" name="loginForm" class="btn btn-primary btn-user btn-block" value="Login">

</form>
</div>
</div>
