<?php if (!empty($this->data['message'])) : ?>
            <div class="notification-container">
        <?php foreach ($this->data['message'] as $error) : ?>
            <?php echo $error; ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>

<div class="register-container">
    <div class="register-container-block">
        <img class="img-register" width="280" height="400" src="/final-project/public/assets/front/img/wolf-font.jpg" alt="image chat pour inscription">
        <div class="register-form">
            <h1>Inscription</h1>
            <div id="error-container" style="color: red;"></div>
            <form class="user-register" action="#" method="post">
                <input type="name" name="name" class="name-form" id="input-name" placeholder="Nom">
                <input type="email" name="email" class="email-form" id="input-email" placeholder="Email">
                <input type="password" name="password" class="pass-form" id="input-password" placeholder="Mot de passe">
                <div class="rgpd-checkbox">
                    <input type="checkbox" name="rgpd" id="rgpd" required>
                    <label for="rgpd">J'accepte les conditions RGPD</label>
                </div>
                <input type="submit" name="registerForm" class="register-btn" value="Register">
            </form>
        </div>
    </div>
</div>
